### ISSUE TITLE
Feature: User can search for a recipe

### ISSUE THREAD

**Issue by MattKweon** [MattKweon/cocktail-card-deck#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to search for a cocktail recipe by name

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a responsive home page with a search bar that allows users to input the name of a cocktail that that want a recipe for

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-26 at 10 09 14 AM](https://user-images.githubusercontent.com/105886708/192339451-df4efb2e-f6c0-4f5f-8d0a-157467b3cc22.png)
![Screen Shot 2022-09-26 at 10 11 29 AM](https://user-images.githubusercontent.com/105886708/192339493-1c6f5f60-7680-482f-8d67-eda107c2f4e2.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a `div.nav-bar` to the HTML.
- [x] Add the logo, app name, and search button to the `div.nav-bar`.
- [x] Search button should remove the 'hidden' class name from the search display if it is current on the hidden view.
- [x] Add rest of div elements with layout class to set up the rest of the HTML.
- [x] Add a background image and overlay to darken the image
- [x] Style the header element to the HTML.
- [x] Style an input element for the search bar to the HTML.
- [x] Style a paragraph element with text content: "recommended..." to the HTML.
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x]  Listen for `'input'` events on the search bar and store the string value of the input to a variable.
- [x] create a data model to store data.
- [x] Listen for `'submit'` events on the search bar that:
  - [x] create a new XMLHttpRequest using the value of the input from the search bar.
  - [x] Prepends the object to the `entries` in the data model.
  - [x] Resets the inputs on the search bar.
- [x] Verify that new search entries are saved to local storage along with the rest of the data model on page reload.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
