### ISSUE TITLE
Feature: User can view details for a recipe

### ISSUE THREAD

**Issue by MattKweon** [MattKweon/cocktail-card-deck#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to view a card that shows an image, name, ingredients lists, and instructions on how to make the drink.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a new display that shows the card of the cocktail that the user would like information on

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-26 at 10 09 26 AM](https://user-images.githubusercontent.com/105886708/192339272-3c3279ea-0129-4e01-b058-ec1528908d5a.png)
![Screen Shot 2022-09-26 at 10 11 37 AM](https://user-images.githubusercontent.com/105886708/192339313-1b028b2d-fb3d-4670-ba5a-e1489e7b6101.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a `'div'` element for a new recipe display view.
- [x] Add dummy data to create a recipe card that shows:
  - [x] Image, cocktail name, ingredients, instructions.
- [x] Style the recipe card.  
- [x] Define a function that creates a DOM tree element for the recipe card that will show:
  - [x] Cocktail image:
    - [x] Create a new XMLHttpRequest using the value of the input from the search bar to find a picture using the image generator AIP.
    - [x] Add the image key- value pair to the corresponding object within the data model. 
  - [x] Title case, capitalized cocktail name with the name in `data.recipe` object.
  - [x] Cocktail ingredients list with the values in `data.recipe` object.
  - [x] Instructions to make cocktail in `data.recipe` object.
- [x] Add the DOM tree to the display view.
- [x] searching for a new recipe should remove the previous DOM tree of the current recipe and add the new recipe card
- [x] Firing the `submit` event listener should change the display to the recipe display view.
- [x] Update the value of the view property to the recipe details display in the data model.
- [x] Ensure that refreshing the page doesn't get rid of the recipe card.
- [x] Ensure that refreshing the pages shows the same view as before refreshing.
- [x] Remove dummy data.
- [x] Make sure the display looks good for both mobile and desktop view.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
