### ISSUE TITLE
Feature: User can add a recipe to their library

### ISSUE THREAD

**Issue by MattKweon** [MattKweon/cocktail-card-deck#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to add a recipe card to a library list of all cocktails recipes they like

## 📐 Functionality

Add a functioning heart button that changes to a filled heart when the user clicks the button. That card will be saved and added their library

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-26 at 10 09 36 AM](https://user-images.githubusercontent.com/105886708/192340009-8b740a15-2ba1-49ba-bab5-c3acd40d73ec.png)
![Screen Shot 2022-09-26 at 10 11 47 AM](https://user-images.githubusercontent.com/105886708/192340028-d48285c3-e442-4eb3-9914-b97551e1d50d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a `div` element for the outline and filled heart button to DOM tree creation function.
- [x] Style the two buttons and hide the filled one.
- [x] Listen for the like button on the click event listener.
- [x] Clicking the like button should:
   - [x] Change the outline heart to a filled heart.
   - [x] Add a property named Id with the value of the nextEntryId from the data model.
   - [x] The value of the `data.recipe` property should be added to the library. property in the data model.
   - [x] increment the value of data.nextEntryId.
 - [x] Style the the button for both mobile and desktop view.
 - [x] Clean up all unnecessary styling.
 - [x] Test the app some more in a private browsing tab.
 - [x]  Fix all errors.
