### ISSUE TITLE
Feature: User can view their library

### ISSUE THREAD

**Issue by MattKweon** [MattKweon/cocktail-card-deck#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to view a card list of all the cocktails they have saved

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a new display that shows the users all the cocktails cards that they have liked and added to library

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-26 at 10 09 50 AM](https://user-images.githubusercontent.com/105886708/192340308-d136115a-d0c3-4cf6-9f78-e9b3ff8bc813.png)
![Screen Shot 2022-09-26 at 10 11 57 AM](https://user-images.githubusercontent.com/105886708/192340324-c7c6e318-590f-4de8-95de-6e708f6c4b9c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a function that changes the view to the correct display based on the value of the `data.view` property.
- [x] Add a `div` for a new library display to the HTML.
- [x] Add a header for the new library display to the HTML.
- [x] Add an anchor element to the nav bar called 'Library'.
- [x] Style the anchor tag.
- [x] Clicking the 'Library' anchor tag should change the value of `data.view` to 'library-display'.
- [x] New recipe card DOM trees should be prepended to the top of the list.
- [x] Heart button should stay filled when changing view to library display. 
- [x] Refreshing the page should should continue showing all saved recipe cards.
- [x] Make display styling looks good for both mobile and desktop view.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
