### ISSUE TITLE
Feature: User can delete an entry from their library

### ISSUE THREAD

**Issue by MattKweon** [MattKweon/cocktail-card-deck#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to delete a cocktail card from their library

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can unlike by clicking the filled heart and have the card removed from their library display

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-26 at 10 10 28 AM](https://user-images.githubusercontent.com/105886708/192340929-0b14ed81-7a55-4e11-9045-d10110bdf908.png)
![Screen Shot 2022-09-26 at 10 11 03 AM](https://user-images.githubusercontent.com/105886708/192340951-7ce1c35c-4d27-4227-a756-634169f07e78.png)
![Screen Shot 2022-09-26 at 10 12 06 AM](https://user-images.githubusercontent.com/105886708/192340975-52911493-d8b6-4d05-9b57-9586b8e6b567.png)
![Screen Shot 2022-09-26 at 10 12 32 AM](https://user-images.githubusercontent.com/105886708/192340997-bf81dd75-1550-49ec-adc2-57b9a10fcfcf.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Listen for a click on the outlined heart button.
- [x] Add a modal to the HTML.
- [x] Style the modal for both mobile and desktop view.
- [x] When users click the heart, a modal should appear asking the user if they want to remove the recipe from their library.

- [x] Clicking on the cancel button should remove the modal
- [x] Clicking the confirm button should:
  - [x] Hide the modal.
  - [x] Remove the cocktail data from the `data.library` property.
  - [x] Remove the DOM tree element for the recipe card.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
